SELECT YEAR(sale.SALES_DATE) YEAR, 
       MONTH(sale.SALES_DATE) MONTH, 
       user.gender GENDER, 
       COUNT(DISTINCT user.USER_ID) USERS
       
FROM USER_INFO user JOIN ONLINE_SALE sale 
     ON user.USER_ID = sale.USER_ID

WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
