SELECT MONTH(car_his.START_DATE) MONTH, car_his.CAR_ID, COUNT(*) RECORDS 

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY car_his
    JOIN 
      (SELECT CAR_ID, COUNT(*) Count
       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
       WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
       GROUP BY CAR_ID) mon_rec
     ON car_his.CAR_ID =  mon_rec.CAR_ID     
           
WHERE mon_rec.Count >= 5 
      AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
 
GROUP BY MONTH(car_his.START_DATE), car_his.CAR_ID
ORDER BY MONTH(car_his.START_DATE) ASC, car_his.CAR_ID DESC