SELECT (CASE WHEN PRICE < 10000 THEN 0
        ELSE TRUNCATE(PRICE,-4) -- TRUNCATE(숫자,버릴 자릿수)_버릴 자릿수 아래로 버림
        END) PRICE_GROUP, COUNT(*) PRICE_GROUP
FROM PRODUCT 
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP