SELECT pro.PRODUCT_ID, pro.PRODUCT_NAME, SUM(AMOUNT * PRICE) TOTAL_SALES
FROM FOOD_PRODUCT pro JOIN FOOD_ORDER ord ON pro.PRODUCT_ID = ord.PRODUCT_ID
WHERE YEAR(ord.PRODUCE_DATE) = '2022' AND MONTH(ord.PRODUCE_DATE) = '5'
GROUP BY 1
ORDER BY TOTAL_SALES DESC, PRODUCT_ID