SELECT APNT_NO, PT_NAME, PATIENT.PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD
FROM  APPOINTMENT INNER JOIN PATIENT ON APPOINTMENT.PT_NO = PATIENT.PT_NO
                  INNER JOIN DOCTOR ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
             
WHERE APNT_YMD LIKE '2022-04-13%'
      AND APPOINTMENT.MCDP_CD = 'CS'
      AND APPOINTMENT.APNT_CNCL_YN = 'N'

ORDER BY APNT_YMD 